spring:
  application:
    name: glmall-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  thymeleaf:
    cache: false
  redis:
    host: 192.168.0.15
server:
  port: 9500

glmall:
  thread:
    core-size: 20
    keep-alive-time: 10
    max-size: 50